service: au-tas-track-covid-19-spread
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    NODE_ENV: ${self:provider.stage}
    MONGO_URL: ${env:MONGO_URL}
    MONGO_DATABASE: ${env:MONGO_DATABASE}
plugins:
  - serverless-offline
  - serverless-domain-manager
functions:
  submitLocationHistory:
    handler: server/index.submitLocationHistory
    events: 
      - http:
          path: /submit-location-history
          method: POST
          cors: true
  getLocationHistory:
    handler: server/index.getLocationHistory
    events: 
      - http:
          path: /location-history
          method: GET
          cors: true
  reportInfected:
    handler: server/index.reportInfected
    events: 
      - http:
          path: /report-infected
          method: PUT
          cors: true
  status:
    handler: server/index.getStatus
    events: 
      - http:
          path: /status
          method: GET
          cors: true
    
custom:
  serverless-offline:
    port: 5001
  customDomain:
    domainName: au-tas-api.trackcovid19spread.com
    basePath: ''
    certificateName: '*.trackcovid19spread.com'
    createRoute53Record: true